### ISSUE TITLE
Bad naming in Heading.hpp

### ISSUE THREAD

**Issue by Nyquase** [zombre98/dems-zia-api#1]
Heading.hpp line 54 :
`std::string path;`
This member should be called 'uri'.

edit: ah yes indeed my bad, i'm not familiar with http protocol

**Comment by Nhyarlathotep** [comment]
+1

**Comment by armandmgt** [comment]
Nope, URI contains the scheme and host while path is just the resource location. See https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
