### ISSUE TITLE
Thread safety of StageManager

### ISSUE THREAD

**Issue by Yuri6037** [zombre98/dems-zia-api#10]
From what I currently read it seam that StageManager is not thread safe which could cause some race conditions with multiple clients being handled at the same time...

**Comment by Kwii-01** [comment]
You still can make it thread safe by using mutex to lock when you use StageManager and Unlock it after.

**Comment by Yuri6037** [comment]
Right mutex could work, but locking everywhere is not always a solution, maybe you could allow creating copies of the StageManager so that each thread would have it's own copy, meaning only the logging based modules would have to lock.
