### ISSUE TITLE
Fichier de Config ?

### ISSUE THREAD

**Issue by pignolr** [zombre98/dems-zia-api#4]
Bonjour,

Du peu de ce je vois, il n'y a pas la possibilité de configurer les différents modules avec un fichier de config. Nous n'avons pas encore travaillé sur les modules donc je ne sais pas si c'est bloquant, mais je trouve ça étrange de ne pas pouvoir les configurer au moins au chargement de ceci. Est-ce normal ?

Merci,
Au revoir.

**Comment by zombre98** [comment]
Merci a toi
