### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Yuri6037** [zombre98/dems-zia-api#9]
The current version of the API will not work under Windows.
The code below :
extern "C" {

  std::string registerHooks(dems::StageManager &manager) {
        manager.request().hookToEnd(0, "MyModule", [](dems::Context &ctx) {
            std::cout << "I'm an example module" << std::endl;
            return dems::CodeStatus::OK;
        });
        return "MyModule";
    }

};

Needs to be replaced by :
extern "C" {

  __declspec(dllexport) std::string registerHooks(dems::StageManager &manager) {
        manager.request().hookToEnd(0, "MyModule", [](dems::Context &ctx) {
            std::cout << "I'm an example module" << std::endl;
            return dems::CodeStatus::OK;
        });
        return "MyModule";
    }

};

**Comment by Kwii-01** [comment]
The api is working on windows, they just didn't show in the example how to do it...

**Comment by Kwii-01** [comment]
And what you write doesn't work on linux, you have to use ifdef _WIN32 / ifdef __linux__ .

**Comment by Kwii-01** [comment]
```extern "C" {
	#ifdef _WIN32
	__declspec( dllexport ) std::string	registerHooks(dems::StageManager &manager)
	#else
	std::string	registerHooks(dems::StageManager &manager)
	#endif
{
return "my module";
}
}```

**Comment by Yuri6037** [comment]
I know I need #ifdef. What I mean is you could have a macro in your API to ease the dev.

EDIT : You could certainly add this code in your AModulesManager.hpp
#ifdef WIN32
#define MODULE_EXPORT __declspec(dllexport)
#else
#define MODULE_EXPORT 
#endif
